Add `do_after_success`, `do_after_failure` callbacks for Linux
Plans can now include `do_after_success` and `do_after_failure`
callback functions. These can be used to run arbitrary commands at the
end of the build process (e.g., notifying external services,
etc.). Both are sufficiently isolated such that an error in a
`do_after_success` callback will not fail the build, nor will it
trigger the `do_after_failure` callback. Additionally, callbacks
cannot influence the exit code of the build as a whole.

Some highlights:

* In order to properly isolate the execution of these callbacks, some
  interesting juggling of Bash error handling had to happen; see
  `_do_final_callback_wrapper` for the gory details.
* To ensure that `do_after_failure` executed after all failures, we
  had to add `EXIT` to the list of trapped signals. Without this,
  exits from the plan or build process (e.g., from `exit_with`) would
  not trigger the callback. It appears that this can cause the failure
  callback to be called twice if _it_ fails, but untrapping `EXIT`
  before `_on_exit` finally exits seems to fix that.

Here's what it the success case looks like:

`plan.sh`:
```
...
do_after_success() {
    build_line "Aww yeah, new package!"
}
...
```

Build Output:
```
★ Signed artifact /hab/cache/artifacts/core-callback-test-pkg-0.1.0-20180515175237-x86_64-linux.hart.
'/hab/cache/artifacts/core-callback-test-pkg-0.1.0-20180515175237-x86_64-linux.hart' -> '/src/results/core-callback-test-pkg-0.1.0-20180515175237-x86_64-linux.hart'
   callback-test-pkg: hab-plan-build cleanup
   callback-test-pkg: 'do_after_success' callback function is defined; executing...
   callback-test-pkg: Aww yeah, new package!
   callback-test-pkg:
   callback-test-pkg: Source Path: /src/callback-test-pkg
   callback-test-pkg: Installed Path: /hab/pkgs/core/callback-test-pkg/0.1.0/20180515175237
   callback-test-pkg: Artifact: /src/results/core-callback-test-pkg-0.1.0-20180515175237-x86_64-linux.hart
   callback-test-pkg: Build Report: /src/results/last_build.env
   callback-test-pkg: SHA256 Checksum: aaee2d1b1b774d91cee0ebf15568b6606d1c46da247fd598d064f6aa440791a6
   callback-test-pkg: Blake2b Checksum: d720bd2263b66a7b5eaee8d6c7577953e749a10cfcbb1768c77d246d07e99296
   callback-test-pkg:
   callback-test-pkg: I love it when a plan.sh comes together.
   callback-test-pkg:
   callback-test-pkg: Build time: 0m0s
```

And here's what the failure case looks like:

`plan.sh`:
```
...

do_install() {
    # intentional failure, for demonstration purposes
    exit_with "Ooops, failed!" 5
}

do_after_failure() {
    build_line "I have failed!"
}
...
```

Build Output:
```
   callback-test-pkg: Installing
mkdir: created directory '/hab/pkgs/core/callback-test-pkg/0.1.0/20180515175644'
ERROR: Ooops, failed!
   callback-test-pkg: Build time: 0m0s
   callback-test-pkg: Exiting on error
   callback-test-pkg: 'do_after_failure' callback function is defined; executing...
   callback-test-pkg: I have failed!
```

Signed-off-by: Christopher Maier <cmaier@chef.io>